"""Generate wire fixtures using Google's runtime and the original .proto."""
import re
from pathlib import Path
from google.protobuf import descriptor_pb2, descriptor_pool, message_factory

ROOT = Path(__file__).resolve().parents[1]
schema = (ROOT / "protocol/nezha-v0.20.5.proto").read_text(encoding="utf-8")
file = descriptor_pb2.FileDescriptorProto(
    name="nezha-v0.20.5.proto", package="proto", syntax="proto3"
)
types = {"double": 1, "float": 2, "uint64": 4, "bool": 8, "string": 9, "bytes": 12}
for name, body in re.findall(r"message\s+(\w+)\s*\{([^}]+)\}", schema):
    message = file.message_type.add(name=name)
    for repeated, typ, field, number in re.findall(
        r"(repeated\s+)?(\w+)\s+(\w+)\s*=\s*(\d+)\s*;", body
    ):
        descriptor = message.field.add(name=field, number=int(number), label=3 if repeated else 1)
        descriptor.type = types.get(typ, 11)
        if typ not in types:
            descriptor.type_name = ".proto." + typ
pool = descriptor_pool.DescriptorPool()
pool.Add(file)
cases = [
    ("host", "Host", dict(
        platform="openwrt", platform_version="24.10.8", cpu=["ARMv8 4 Core"],
        mem_total=536870912, disk_total=134217728, arch="aarch64",
        boot_time=1700000000, version="0.20.5-zig",
    )),
    ("state", "State", dict(
        cpu=12.5, mem_used=1024, swap_used=256, disk_used=512,
        net_in_transfer=3000, net_out_transfer=4000, net_in_speed=30,
        net_out_speed=40, uptime=60, load1=0.1, load5=0.2, load15=0.3,
        tcp_conn_count=17, udp_conn_count=8, process_count=100,
    )),
    ("result", "TaskResult", dict(id=150, type=2, delay=1.25, data="ok", successful=True)),
]
lines = ["// Generated by tests/generate_proto_vectors.py using Google Protobuf 6.32.1.",
         "// Source schema is copied verbatim from agent v0.20.5.", ""]
for label, name, values in cases:
    cls = message_factory.GetMessageClass(pool.FindMessageTypeByName("proto." + name))
    encoded = cls(**values).SerializeToString(deterministic=True)
    lines.append("pub const " + label + " = [_]u8{")
    for offset in range(0, len(encoded), 12):
        lines.append("    " + ", ".join(f"0x{v:02x}" for v in encoded[offset:offset + 12]) + ",")
    lines.extend(["};", ""])
path = ROOT / "src/testdata/proto_v0_20_5.zig"
path.parent.mkdir(exist_ok=True)
path.write_text("\n".join(lines), encoding="utf-8")
print("Generated", path)
